<?php

return [


	/**
	 * see documentation AdminLTE3 on https://adminlte.io/docs/3.0/
	 * 
	 *
	 * options color : blue, secondary, success, green, info, cyan, warning, yellow, red, danger, black, gray-dark, gray, light, indigo, navy, purple, fuchsia, pink, maroon, orange, lime, teal, olive
	 * type/mode : dark, light
	 */
	'navbar' => [
		'bg-white' => 'main-header navbar navbar-expand navbar-white navbar-dark',
		'bg-primary' => 'main-header navbar navbar-expand navbar-primary navbar-dark',
		'bg-secondary' => 'main-header navbar navbar-expand navbar-secondary navbar-dark',
		'bg-info' => 'main-header navbar navbar-expand navbar-info navbar-dark',
		'bg-success' => 'main-header navbar navbar-expand navbar-success navbar-dark',
		'bg-danger' => 'main-header navbar navbar-expand navbar-danger navbar-dark',
		'bg-indigo' => 'main-header navbar navbar-expand navbar-indigo navbar-dark',
		'bg-purple' => 'main-header navbar navbar-expand navbar-purple navbar-dark',
		'bg-pink' => 'main-header navbar navbar-expand navbar-pink navbar-dark',
		'bg-navy' => 'main-header navbar navbar-expand navbar-navy navbar-dark',
		'bg-lightblue' => 'main-header navbar navbar-expand navbar-lightblue navbar-dark',
		'bg-teal' => 'main-header navbar navbar-expand navbar-teal navbar-dark',
		'bg-dark' => 'main-header navbar navbar-expand navbar-dark navbar-dark',
		'bg-gray-dark' => 'main-header navbar navbar-expand navbar-gray-dark navbar-dark',
		'bg-gray' => 'main-header navbar navbar-expand navbar-gray navbar-dark',
		'bg-light' => 'main-header navbar navbar-expand navbar-light navbar-light',
		'bg-warning' => 'main-header navbar navbar-expand navbar-warning navbar-light',
		'bg-white' => 'main-header navbar navbar-expand navbar-white navbar-light',
		'bg-orange' => 'main-header navbar navbar-expand navbar-orange navbar-light'
	],
	'sidebar' => [
		'dark bg-primary' => 'sidebar-dark-primary',
	    'dark bg-warning' => 'sidebar-dark-warning',
	    'dark bg-info' => 'sidebar-dark-info',
	    'dark bg-danger' => 'sidebar-dark-danger',
	    'dark bg-success' => 'sidebar-dark-success',
	    'dark bg-indigo' => 'sidebar-dark-indigo',
	    'dark bg-lightblue' => 'sidebar-dark-lightblue',
	    'dark bg-navy' => 'sidebar-dark-navy',
	    'dark bg-purple' => 'sidebar-dark-purple',
	    'dark bg-fuchsia' => 'sidebar-dark-fuchsia',
	    'dark bg-pink' => 'sidebar-dark-pink',
	    'dark bg-maroon' => 'sidebar-dark-maroon',
	    'dark bg-orange' => 'sidebar-dark-orange',
	    'dark bg-lime' => 'sidebar-dark-lime',
	    'dark bg-teal' => 'sidebar-dark-teal',
	    'dark bg-olive' => 'sidebar-dark-olive',
	    'light bg-primary' => 'sidebar-light-primary',
	    'light bg-warning' => 'sidebar-light-warning',
	    'light bg-info' => 'sidebar-light-info',
	    'light bg-danger' => 'sidebar-light-danger',
	    'light bg-success' => 'sidebar-light-success',
	    'light bg-indigo' => 'sidebar-light-indigo',
	    'light bg-lightblue' => 'sidebar-light-lightblue',
	    'light bg-navy' => 'sidebar-light-navy',
	    'light bg-purple' => 'sidebar-light-purple',
	    'light bg-fuchsia' => 'sidebar-light-fuchsia',
	    'light bg-pink' => 'sidebar-light-pink',
	    'light bg-maroon' => 'sidebar-light-maroon',
	    'light bg-orange' => 'sidebar-light-orange',
	    'light bg-lime' => 'sidebar-light-lime',
	    'light bg-teal' => 'sidebar-light-teal',
	    'light bg-olive' => 'sidebar-light-olive'
	],
	'brand' => [
		'bg-primary' => 'bg-primary',
	    'bg-warning' => 'bg-warning',
	    'bg-info' => 'bg-info',
	    'bg-danger' => 'bg-danger',
	    'bg-success' => 'bg-success',
	    'bg-indigo' => 'bg-indigo',
	    'bg-lightblue' => 'bg-lightblue',
	    'bg-navy' => 'bg-navy',
	    'bg-purple' => 'bg-purple',
	    'bg-fuchsia' => 'bg-fuchsia',
	    'bg-pink' => 'bg-pink',
	    'bg-maroon' => 'bg-maroon',
	    'bg-orange' => 'bg-orange',
	    'bg-lime' => 'bg-lime',
	    'bg-teal' => 'bg-teal',
	    'bg-olive' => 'bg-olive',
	    'bg-light' => 'bg-light',
	    'bg-white' => 'bg-white',
	    'bg-gray' => 'bg-gray',
	    'bg-gray-dark' => 'bg-gray-dark',
	    'bg-dark' => 'bg-dark'
	],
	'accent' => [
		'bg-primary' => 'accent-primary',
	    'bg-warning' => 'accent-warning',
	    'bg-info' => 'accent-info',
	    'bg-danger' => 'accent-danger',
	    'bg-success' => 'accent-success',
	    'bg-indigo' => 'accent-indigo',
	    'bg-lightblue' => 'accent-lightblue',
	    'bg-navy' => 'accent-navy',
	    'bg-purple' => 'accent-purple',
	    'bg-fuchsia' => 'accent-fuchsia',
	    'bg-pink' => 'accent-pink',
	    'bg-maroon' => 'accent-maroon',
	    'bg-orange' => 'accent-orange',
	    'bg-lime' => 'accent-lime',
	    'bg-teal' => 'accent-teal',
	    'bg-olive' => 'accent-olive'
	],
	'bg' => [
		'bg-primary',
	    'bg-warning',
	    'bg-info',
	    'bg-danger',
	    'bg-success',
	    'bg-indigo',
	    'bg-lightblue',
	    'bg-navy',
	    'bg-purple',
	    'bg-fuchsia',
	    'bg-pink',
	    'bg-maroon',
	    'bg-orange',
	    'bg-lime',
	    'bg-teal',
	    'bg-olive',
	    'bg-dark',
	    'bg-white',
	    'bg-light',
	    'bg-gray' => 'bg-gray',
	    'bg-gray-dark' => 'bg-gray-dark'
	],


];